sudo: false
language: node_js
node_js:
 - "7.6"

script:
 - yarn bootstrap
 - yarn lint
 - yarn build:runtime
 - yarn env:webpack-1
 - yarn coverage
 - yarn env:webpack-2
 - yarn coverage

env:
  global:
    - ISTANBUL_COVERAGE: yes

after_success:
 - npm run coverage-upload:coveralls
