sudo: false
language: node_js
node_js:
  - "7.6"

script: npm run lint && npm test

env:
  global:
    - ISTANBUL_COVERAGE: yes

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
